#!/bin/bash

brew install aom
brew install glib
brew install libbluray
brew install little-cms2
brew install openssl@1.1
brew install sassc
brew install arpack
brew install gmp
brew install libde265
brew install lua
brew install opus
brew install sdl2
brew install autoconf
brew install gnu-sed
brew install libevent
brew install lzip
brew install p11-kit
brew install shared-mime-info
brew install automake
brew install gnutls
brew install libffi
brew install lzo
brew install pcre
brew install snappy
brew install cairo
brew install go
brew install libheif
brew install maven
brew install pcre2
brew install speex
brew install ctop
brew install goenv
brew install libidn2
brew install mongodb-community
brew install peco
brew install sqlite
brew install eigen
brew install graphite2
brew install libmpc
brew install mpfr
brew install perl
brew install terminal-notifier
brew install epstool
brew install harfbuzz
brew install libogg
brew install mysql@5.6
brew install pixman
brew install tesseract
brew install ffmpeg
brew install heroku
brew install libomp
brew install mysql@5.7
brew install pkg-config
brew install tfenv
brew install fftw
brew install heroku-node
brew install libpng
brew install ncurses
brew install postgresql
brew install theora
brew install flac
brew install httpie
brew install libsamplerate
brew install nettle
brew install puma-dev
brew install tmux
brew install fontconfig
brew install hwloc
brew install libsass
brew install nginx
brew install pyenv
brew install tree
brew install freetype
brew install icarus-verilog
brew install libsndfile
brew install nkf
brew install python
brew install unbound
brew install frei0r
brew install icu4c
brew install libsoxr
brew install node
brew install python@3.8
brew install unison
brew install fribidi
brew install ilmbase
brew install libtasn1
brew install node-build
brew install rbenv
brew install vim
brew install fswatch
brew install imagemagick
brew install libtiff
brew install nodenv
brew install readline
brew install webp
brew install gcc
brew install isl
brew install libtool
brew install open-mpi
brew install redis
brew install wget
brew install gdb
brew install jpeg
brew install libunistring
brew install openblas
brew install ripgrep
brew install x264
brew install gdbm
brew install krb5
brew install libvidstab
brew install opencore-amr
brew install rtmpdump
brew install x265
brew install gettext
brew install lame
brew install libvorbis
brew install openexr
brew install rubberband
brew install xvid
brew install ghostscript
brew install leptonica
brew install libvpx
brew install openjpeg
brew install ruby
brew install xz
brew install giflib
brew install libass
brew install libyaml
brew install openssl
ruby-build hoge
yarn